### PR TITLE
Assignments

### PR DESCRIPTION
**Pull request by gottacatchenall**
Still need to sort assignments based on date when querying db

### CODE REVIEW

**Comment by gottacatchenall** [comment]
🐳🐳🐳🐳🐳🐳🐳🐳🐳🐳

**Comment by laba2346** [comment]
👎👎👎👎👎👎👎👎👎👎👎👎

**Comment by gottacatchenall** [comment]
these are the type of commits you get if you val**grind** 🙌🏼👏🙏💯💯💯

**Comment by laba2346** [comment]
i can't help but  **React** positively to this request 🙏 👏 👍 🙌 👀

**Comment by gottacatchenall** [comment]
oh then just wait for the **sql**

**Comment by laba2346** [comment]
sq**Well**, i cant wait! 💯

**Comment by gottacatchenall** [comment]
oh give it a **REST**

**Pull request merged**
